Fix build error on Rust 1.13
```
error[E0046]: not all trait items implemented, missing: `description`
  --> src/lib.rs:77:1
   |
77 | impl Error for Errno {}
   | ^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
```