Add minimum lines for ::std::error::Error implementation (#29)
* Add minimum lines for ::std::error::Error implementation

To compile below with current (1.47) rustc:

    fn f<E: ::std::error::Error>(e: E) {}
    fn main() {
        f(errno::Errno(0));
    }

* Fix build error on Rust 1.13

```
error[E0046]: not all trait items implemented, missing: `description`
  --> src/lib.rs:77:1
   |
77 | impl Error for Errno {}
   | ^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
```

Co-authored-by: Chris Wong <lambda.fairy@gmail.com>